include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-r619ac-status
PKG_VERSION:=1
PKG_RELEASE:=1

LUCI_TITLE:=Modify the summary of luci for r619ac route
LUCI_PKGARCH:=all

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
